### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by du82** [tatsumoto-ren/tatsumoto-ren.github.io#22]
I like the theme of the site, and would like to use it with my own content, mainly focused on cybersecurity and privacy. I don't see any license on the GitHub, so could I please do that?

I wouldn't include any content from your site besides a link to your GitHub if you wish, and would use it for my own site with my own original content.

**Comment by tatsumoto-ren** [comment]
>I like the theme of the site, and would like to use it with my own content, mainly focused on cybersecurity and privacy. I don't see any license on the GitHub, so could I please do that?

Feel free to copy and/or modify anything except the articles themselves. 

>I don't see any license on the GitHub

I'm not sure how to license this repo because it contains both the html/css/js code and the texts of the articles. The code should be GPLv3. But the articles can't be licensed under GPL because they're not programs. Any advice would be appreciated.

**Comment by du82** [comment]
> > I like the theme of the site, and would like to use it with my own content, mainly focused on cybersecurity and privacy. I don't see any license on the GitHub, so could I please do that?
> 
> Feel free to copy and/or modify anything except the articles themselves.
> 
> > I don't see any license on the GitHub
> 
> I'm not sure how to license this repo because it contains both the html/css/js code and the texts of the articles. The code should be GPLv3. But the articles can't be licensed under GPL because they're not programs. Any advice would be appreciated.

I'd recommend a dual-license. GPLv3 for the code, and I'd recommend the Creative Commons CC BY-NC-SA 4.0 license for the content. https://creativecommons.org/licenses/by-nc-sa/4.0
