### ISSUE TITLE
Petition for Arco Linux to be added as  one of the best possible Arch based distros in the recommended gnu/linux tool

### ISSUE THREAD

**Issue by chrollorifat** [tatsumoto-ren/tatsumoto-ren.github.io#29]
I want to let you know that I have found outstanding support and flexibility in ArcoLinux for learning Japanese following the Ajatt philosophy. But, sadly, it is not on the list of recommended arch-based distros on the Our Immersion Learning tools page. IMO, it is the best arch-based distro for learning Japanese and for general use. Don't take my word for it, research yourself and also search Erik Dubois ( the creator of arco) on YouTube. Dude literally made almost 4k videos regarding any problems that you may encounter in using the distro. It also has an active telegram channel. So there is no lack of support for anything. Therefore, I think it should be added as a recommended arch-based distro.

**Comment by tatsumoto-ren** [comment]
Yeah feel free to make a PR that adds it to the list. Personally I don't know anything about the distro, so I searched it and found a number of pretty confusing websites. Not sure which is the main one. There's arcolinux.info and arcolinux.com and arcolinuxd.com and all of them are overloaded with information.

**Comment by chrollorifat** [comment]
@tatsumoto-ren this is the page that gives you the overview of the different isos and the distro: https://www.arcolinux.info/downloads/
