### ISSUE TITLE
Add Search box to find things easily. 

### ISSUE THREAD

**Issue by objestik** [tatsumoto-ren/tatsumoto-ren.github.io#4]
Self-explanatory.

**Comment by tatsumoto-ren** [comment]
Implemented a search button at the top. 

<img width="100%" alt="Image" src="https://github.com/user-attachments/assets/518093ab-039b-41ab-8076-b930c16b384e" />

**Comment by tatsumoto-ren** [comment]
Now live: https://ajatt.top/blog/search.html
